classDiagram

    valuesMap --> valuesMapItem
    valuesMapItem --> valuesMapValueItem : values contains
    class valuesMap {
    }
    
    class valuesMapItem {
        String type
        Object[] values
    }

    note for valuesMapValueItem "This is anyOf number, string, boolean, or Point"
    class valuesMapValueItem {

    }
